# Welcome to serverless. Read the docs
# https://serverless.com/framework/docs/

# Serverless.yml is the configuration the CLI
# uses to deploy your code to your provider of choice

# The `service` block is the name of the service
service: weather-app

# The `provider` block defines where your service will be deployed
provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1

# The `functions` block defines what code to deploy
functions:
  # Test endpoint - helloworld
  helloWorld:
    handler: handler.helloWorld
    events:
      - http:
          path: hello-world
          method: get
          cors: true
  # Fetch weather by city
  getCityWeather:
    handler: handler.getCityWeather
    events:
      - http:
          path: weather/city
          method: get
          cors: true
